---
- name: Development System
  hosts: development

  roles:
    # Common must come first
    - common

    # Other roles are less order dependent
    - 1password
    - android_ndk
    - asdf
    - aws
    - cpp
    - discord
    - docker
    - firefox
    - fwup
    - github_cli
    - libcurl
    - libogg
    - libopus
    - libssl
    - protobuf
    - python
    - rust
    - tailscale
    - tlp
    #- trivy (Doesn't support 24.04 yet)
    - vscode
    - zsh
