- name: Install libssl (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: libssl-dev
    state: present
  become: true

- name: Install libssl (Mac)
  when: ansible_os_family == 'Darwin'
  homebrew:
    name: 
      - openssl@1.1
      - openssl@3
    state: present
