
- name: Setup Trivy (Ubuntu 22.04)
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu' and ansible_facts['distribution_version'] == '22.04'
  block:
    - name: Add trivy signing key
      ansible.builtin.get_url:
        url: https://aquasecurity.github.io/trivy-repo/deb/public.key
        dest: /tmp/trivy.key
        mode: '0644'
        force: true
      become: true

    - name: Dearmor trivy key
      ansible.builtin.shell: cat /tmp/trivy.key | gpg --dearmor > /etc/apt/trusted.gpg.d/trivy.gpg
      become: true

    - name: Add trivy repository
      ansible.builtin.apt_repository:
        repo: deb https://aquasecurity.github.io/trivy-repo/deb jammy main
        filename: trivy
        state: present
      become: true

    - name: Install trivy
      ansible.builtin.apt:
        name: trivy
        state: present
      become: true