
- name: Install C/C++ Build Tools
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    pkg:
      - build-essential
      - gcovr
      - clang
      - clang-tidy
      - clang-format
      - pkg-config
      - ninja-build
      - python3-pip
      - meson
    state: latest
  become: true

