- name: Setup VSCode (Debian)
  when: ansible_facts['os_family'] == 'Debian'
  block:
  - name: Install vscode apt key
    ansible.builtin.get_url:
      url: https://packages.microsoft.com/keys/microsoft.asc
      dest: /etc/apt/trusted.gpg.d/microsoft.asc
      mode: '0644'
      force: true
    become: true

  - name: Install vscode apt repository
    ansible.builtin.apt_repository:
      repo: deb [arch=amd64,arm64] https://packages.microsoft.com/repos/code stable main
      filename: vscode
      state: present
    become: true

  - name: Install vscode
    ansible.builtin.apt:
      name: code
      state: present
    become: true

- name: Install VSCode (Mac)
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present