- name: Install Steam (Debian)
  when: ansible_facts['os_family'] == 'Debian'
  block:
    - name: Check if i386 is enabled
      ansible.builtin.command: dpkg --print-foreign-architectures | grep i386
      register: i386_enabled
      changed_when: false
      failed_when: false

    - name: Add i386 Architecture
      when: i386_enabled.rc == 0
      block:
        - name: Add dpkg architecture
          ansible.builtin.command: dpkg --add-architecture i386
          become: true
        - name: Perform an apt update
          ansible.builtin.apt:
            update_cache: yes
          become: true

    - name: Add steam signing key
      ansible.builtin.get_url:
        url: https://repo.steampowered.com/steam/archive/stable/steam.gpg
        dest: /etc/apt/trusted.gpg.d/steam.gpg
        mode: '0644'
        force: true
      become: true

    - name: Add steam repository
      when: ansible_facts['distribution_version'] == '24.04'
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64,i386] https://repo.steampowered.com/steam/ stable steam
        filename: steam-stable
        state: present
      become: true

    - name: Divert Steam Repository Config (Beta)
      community.general.dpkg_divert:
        path: /etc/apt/sources.list.d/steam-beta.list
        divert: /etc/apt/sources.list.d/steam-beta.list.dpkg-steamlauncher
      become: true

    - name: Divert Steam Repository Config (Stable)
      community.general.dpkg_divert:
        path: /etc/apt/sources.list.d/steam-stable.list
        divert: /etc/apt/sources.list.d/steam-stable.list.dpkg-steamlauncher
      become: true

    - name: Install steam
      ansible.builtin.apt:
        state: present
        name: steam-launcher
      become: true
