- name: Install python3 (Debian)
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    name:
      - python3
      - python3-pip
    state: present
  become: true

- name: Install python3 (Mac)
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew:
    name: python3
    state: present

