- name: Setup Tailscale (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Add tailscale signing key
      when: ansible_facts['distribution_version'] == '22.04'
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
        dest: /etc/apt/trusted.gpg.d/tailscale.gpg
        mode: '0644'
        force: true
      become: true
    
    - name: Add tailscale signing key
      when: ansible_facts['distribution_version'] == '24.04'
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/noble.noarmor.gpg
        dest: /etc/apt/trusted.gpg.d/tailscale.gpg
        mode: '0644'
        force: true
      become: true

    - name: Add tailscale repository
      when: ansible_facts['distribution_version'] == '22.04'
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
        filename: tailscale
        state: present
      become: true
    
    - name: Add tailscale repository
      when: ansible_facts['distribution_version'] == '24.04'
      ansible.builtin.apt_repository:
        repo: deb https://pkgs.tailscale.com/stable/ubuntu noble main
        filename: tailscale
        state: present
      become: true

    - name: Divert Tailscale Repository Config
      community.general.dpkg_divert:
        path: /etc/apt/sources.list.d/tailscale.list
        divert: /etc/apt/sources.list.d/tailscale.list.dpkg-tailscale
      become: true

    - name: Install tailscale client
      ansible.builtin.apt:
        state: present
        name: tailscale
      become: true
