- name: Apply Gnome Customizations
  when:
    - ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Install Config Editors
      apt:
        name:
          - dconf-editor
          - gnome-shell-extension-prefs
        state: present
      become: true
    - name: Enable Minimize on Dock Click
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/click-action"
        value: "'minimize'"
        state: present
    - name: Move Dock to the Bottom
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
        value: "'BOTTOM'"
        state: present
    - name: Disable Dock Extend to the Screen Edge
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
        value: "false"
        state: present
    - name: Disable system font
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
        value: "false"
        state: present
    - name: Disable theme colors
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
        value: "false"
        state: present
    - name: Set terminal background color
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
        value: "'rgb(23,20,33)'"
        state: present
    - name: Set terminal foreground color
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
        value: "'rgb(208,207,204)'"
        state: present
    - name: Set terminal font
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
        value: "'FiraMono Nerd Font 10'"
        state: present
      