- name: Install libopus (Debian)
  when: ansible_os_family == 'Debian'
  apt:
    name: libopus-dev
    state: present
  become: true

- name: Install libopus (Mac)
  when: ansible_os_family == 'Darwin'
  homebrew:
    name:
      - libopusenc
      - opus
      - opus-tools
      - opusfile
    state: present
