- name: Install Discord (Ubuntu)
  when: ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Install Discord Snap
      community.general.snap:
          name: discord
          channel: latest/stable
      become: true

    - name: Connect Discord to system-observe
      ansible.builtin.shell: snap connect discord:system-observe
      become: true

- name: Install Discord (Mac)
  when: ansible_facts['os_family'] == 'Darwin'
  community.general.homebrew_cask:
    name: discord
    state: present