- name: Install Discord
  when: ansible_facts['os_family'] == 'Debian' and ansible_facts['distribution'] == 'Ubuntu'
  block:
    - name: Install Discord Snap
      community.general.snap:
          name: discord
          channel: latest/stable
      become: true

    - name: Connect Discord to system-observe
      ansible.builtin.shell: snap connect discord:system-observe
      become: true

