- name: Create Home Assistant Config Directory
  ansible.builtin.file:
    path: /opt/home-assistant
    state: directory
  become: true

- name: Start Home Assistant Container
  community.docker.docker_container:
    name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    image_name_mismatch: recreate
    pull: true
    state: started
    restart_policy: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /opt/home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  become: true